Minor changes to faq
pythonindia/inpycon2017 pull request #12
Opened 2017-07-03 15:42 UTC by Tabs16

Hello,
I have made some grammatical changes to FAQ section. Moreover, I have fixed the navbar to the top in order to allow the user to jump to any section easily. 
Please review :)

2017-07-04 12:29 UTC, CuriousLearner requested changes
Hi, 

Thanks for your contribution!

The logo gets stripped off with the fixed header. Can you please fix that?

<img width="1231" alt="screen shot 2017-07-04 at 5 57 20 pm" src="https://user-images.githubusercontent.com/8039608/27830084-62466160-60e2-11e7-9e11-b26676f84bbd.png">

2017-07-04 16:12 UTC, Tabs16 commented
@CuriousLearner ,done :)

2017-07-07 17:30 UTC, CuriousLearner requested changes
Review mentioned inline.

2017-07-07 17:30 UTC, CuriousLearner commented on css/custom.css
> +.col-md-8 {
Not a good way to play with bootstrap grid. Please use classes as needed.

You do not need to add extra style to `col-md-8`.

Also, the logo gets stripped off on small screens:

<img width="670" alt="screen shot 2017-07-07 at 10 56 56 pm" src="https://user-images.githubusercontent.com/8039608/27969290-eb8ea19e-6367-11e7-85e6-c55ed07fa986.png">

2017-07-09 06:06 UTC, theskumar commented
Hi @Tabs16, there was of change to html theme section and the latest is not available at https://pythonindia.github.io/inpycon2017/faqs.html

I've to close this PR, since it can not be merged. If you think there are any issue with the current FAQs would be happy to merge any PRs. 

Thanks again!

2017-07-09 06:06 UTC, closed without merging