[Enchancement] Date and Venue redirected
pythonindia/inpycon2017 pull request #120
Opened 2017-09-25 14:20 UTC by vipulgupta2048

The date now redirects to make a new calendar entry in Google Calendar for the user.
Venue redirects to maps API in the map section of the website.

2017-09-26 20:25 UTC, realslimshanky requested changes
You need to make changes to `templates/index.html` and then build using static jinja instead of editing directly to the generated file.

2017-09-27 00:16 UTC, vipulgupta2048 commented
Rookie mistake, my bad. Won't happen again. 
Well, done now. Learnt something new. 
Also I am unsure of as to how there are changes in index.html now. I didn't even open that file. I didn't change anything there. Yet everytime I did git diff, it showed changes.

2017-09-27 04:57 UTC, CuriousLearner requested changes
Please see the review inline. 

Also for generating actual pages from templates, please use static jinja (Read the `README`)

2017-09-27 04:57 UTC, CuriousLearner commented on index.html
> +            <a href="http://www.zeomega.com/" target="_blank">
This is supposed to open up a modal. In the modal, you can link their website which can open in another tab.

2017-09-27 05:32 UTC, CuriousLearner commented on index.html
> +            <a href="http://www.zeomega.com/" target="_blank">
So, rever the code where you've removed the modal code :) and do the changes for the link in the modal itself.

2017-09-30 06:16 UTC, realslimshanky commented
@vipulgupta2048 you can close this PR since you have created a new one i.e. #124

2017-09-30 06:31 UTC, closed without merging