Aligning Pipal Academy logo at center.
pythonindia/inpycon2017 pull request #150
Opened 2017-10-15 17:46 UTC by emht

#149

2017-10-15 18:42 UTC, emht commented
@realslimshanky @CuriousLearner review and suggest any changes if any.

2017-10-15 21:14 UTC, realslimshanky requested changes
Please go through the comment and make the appropriate change to align the logo in a better way on mobile devices.

2017-10-15 21:14 UTC, realslimshanky commented on css/main.css
> +    margin-left: 25%;
You need to try making `margin-left: 0%` here as `25%` does not look good on mobile devices.
![image](https://user-images.githubusercontent.com/10004530/31589228-d2bf26cc-b21b-11e7-9f8e-68631bd2d783.png)

2017-10-16 11:13 UTC, realslimshanky approved these changes

2017-10-16 11:13 UTC, merged