Link for volunteer form added
pythonindia/inpycon2017 pull request #41
Opened 2017-07-14 15:22 UTC by krishamehta

2017-07-14 16:31 UTC, CuriousLearner requested changes
Apart from the review mentioned inline, the changes should be made in templates file and reflected HTML pages should be added in the PR. Please read the `README.md` on how to do it.

2017-07-14 16:31 UTC, CuriousLearner commented on faqs.html
> +													<p><span>A.</span>Please share your details by filling this <a href = "https://docs.google.com/forms/d/1WXkev5oYAw9KiW0H6viIB7c3S-wRkFRI8BCCcctdkLk">form</a> and the team will soon get b
The link to the form should be this: http://bit.ly/inpycon2017

2017-07-18 05:13 UTC, CuriousLearner commented
Hey @krishamehta 

Just wanted to ping you to know the status of this. Will you be able to make changes to the PR?

2017-07-18 05:26 UTC, krishamehta commented
Yes I'll do it by today

2017-07-18 05:30 UTC, CuriousLearner commented
Thanks for the update!

2017-07-22 05:12 UTC, CuriousLearner commented
Hey @krishamehta

Would you be able to pick this up, or someone else should go with it?

2017-07-22 05:13 UTC, CuriousLearner requested changes
Also, please do the changes in `templates/faqs.html` and then regenerate the HTML

2017-07-23 13:48 UTC, CuriousLearner requested changes

2017-07-23 13:48 UTC, CuriousLearner commented on templates/faqs.html
> +													<p><span>A.</span>Please share your details by filling this <a href = " http://bit.ly/inpycon2017">form</a> and the team will soon get back to you with responsibilities according to the
Please do not leave space in the hyperlink reference tag.

`<a href="http://bit.ly/inpycon2017">form</a>`

Also, please generate the HTML and it in this PR.

2017-07-23 13:49 UTC, CuriousLearner commented on templates/faqs.html
> +													<p><span>A.</span>Please share your details by filling this <a href = " http://bit.ly/inpycon2017">form</a> and the team will soon get back to you with responsibilities according to the
Please resolve conflicts with the base master branch.

If possible, do a rebase.

2017-07-23 13:53 UTC, krishamehta commented on templates/faqs.html
> +													<p><span>A.</span>Please share your details by filling this <a href = " http://bit.ly/inpycon2017">form</a> and the team will soon get back to you with responsibilities according to the
ya ya working on it

2017-07-26 08:24 UTC, CuriousLearner commented
Due to no response on PR from a long time, this is resolved in 1a470b681f76c68e8f959d8fc32cab383639c6dc

2017-07-26 08:24 UTC, closed without merging