[FIX #34] SIze of  social media links
pythonindia/inpycon2017 pull request #51
Opened 2017-07-14 18:53 UTC by amoghj8

The size of social media links have been altered.

2017-07-14 19:01 UTC, pradeepgangwar commented
@amoghj8 when you are making changes for front-end task. And you can serve your site on gh-pages. Always include a link (gh-pages live link) in PR to view those changes. 
Although i am not a reviewer but surely it makes task of reviewers easy.

2017-07-14 19:14 UTC, amoghj8 commented
Thanks for the info @pradeepgangwar , I haven't done that before. Should I add gh-page to my forked repo?

2017-07-14 19:24 UTC, pradeepgangwar commented
@amoghj8 Yes, and paste a link here for reviewers to see it :+1:

2017-07-18 05:29 UTC, CuriousLearner commented on css/main.css
> +@media screen and (max-width: 767px) {
This `max-width` 767 px and `min-width` 768 px is really odd.

Can we improve it?

2017-07-18 05:29 UTC, CuriousLearner requested changes
I've left my review in-line.

Thanks for your contributions @amoghj8 !

2017-07-18 07:39 UTC, amoghj8 commented on css/main.css
> +@media screen and (max-width: 767px) {
@CuriousLearner  How about "Responsive utilities" of bootstrap? We can edit the sizes using visible or hidden classes.

2017-07-18 19:22 UTC, SaptakS commented on css/main.css
> +@media screen and (max-width: 767px) {
@amoghj8 the thing what @CuriousLearner is trying to say I believe is you can set either one (wither max-width or min-width) and set the other as the default font-size. So something like by default it is 2em, but if media screen width below 767px (i.e max-width:767px) then `font-size:1.5em`. Keeping both max-width and min-width is weird.

2017-07-19 02:50 UTC, amoghj8 commented on css/main.css
> +@media screen and (max-width: 767px) {
@SaptakS  Oh ! That's true. Sorry for the silly mistake.

2017-07-19 09:02 UTC, sayanchowdhury commented on css/main.css
> +@media screen and (max-width: 767px) {
Just update the PR

2017-07-22 05:20 UTC, CuriousLearner commented
Hey @amoghj8 !

Can you please resolve the conflicts so that we can review and get this merged in?

2017-07-23 13:30 UTC, amoghj8 commented
@CuriousLearner  Resolved the conflicts

2017-07-23 13:33 UTC, CuriousLearner commented
@saptakS Reviews?

2017-07-23 13:42 UTC, SaptakS approved these changes

2017-07-23 13:45 UTC, CuriousLearner approved these changes
LGTM!

Thanks for your contributions! Merging in!

2017-07-23 13:45 UTC, merged