changes made in logo and index.html file
pythonindia/inpycon2017 pull request #6
Opened 2017-06-27 06:55 UTC by rajataaron

Changes made in logo color of toggle button and added some space into section.

2017-06-27 07:09 UTC, CuriousLearner requested changes

2017-06-27 07:09 UTC, CuriousLearner commented on css/custom.css
> +.section-head{
Leave a space between selector and starting braces

2017-06-27 07:09 UTC, CuriousLearner commented on css/custom.css
>  .navbar-brand img{
Same here.

2017-06-27 10:32 UTC, theskumar reviewed
Minor feedback and rest look good.

2017-06-27 10:32 UTC, theskumar commented on css/custom.css
> +    margin-top: 50px;
This is going to affect both the mobile and desktop view. Please make sure this only on desktop view. :)

2017-06-28 03:55 UTC, theskumar approved these changes

2017-06-28 06:01 UTC, merged

2017-06-28 06:02 UTC, akshayaurora commented
@rajataaron 👍 thanks