[Fix #56] Fixed statistics mobile view for some resolution
pythonindia/inpycon2017 pull request #61
Opened 2017-07-17 14:12 UTC by pradeepgangwar

Issue No. - #56 
Link to view Changes - [Gh-Pages](http://pradeepgangwar.tech/inpycon2017/)

**Changes Made:**
- Added **media CSS** query for particular resolution as bootstrap grid didn't solved the problem even with full implementation.

2017-07-17 16:53 UTC, CuriousLearner requested changes
Can you please use default bootstrap classes?

Also, please avoid inline styling.

2017-07-17 17:21 UTC, pradeepgangwar commented
In my **merged PR** #30 . I Implemented changes for mobile view using only bootstrap. But #56 issue was raised. Actually problem was with only between **resolution 480px to 569px**, so I decided to change it using media queries which will not affect other classes on website. 
I removed inline styles.

2017-07-18 05:07 UTC, CuriousLearner commented
Breakpoints eventually cause trouble when the code base size increases. Can you please use bootstrap grid instead?

2017-07-18 07:04 UTC, pradeepgangwar commented
@CuriousLearner I have fixed it now with **bootstrap grid** only. The problem was caused by a supportive CSS file that had such rules for that resolution. The issue looks fixed now.

2017-07-22 05:25 UTC, CuriousLearner commented on css/main.css
> +}
Leave a line at the end of the file.

2017-07-22 06:00 UTC, pradeepgangwar commented on css/main.css
> +}
@CuriousLearner  done :+1:

2017-07-23 22:11 UTC, realslimshanky commented on css/main.css
> +}
@pradeepgangwar your new commit has been added to this PR when you pushed. The review you are seeing is showing the code at the moment of review and it'll remain same.

2017-07-24 01:22 UTC, pradeepgangwar commented on css/main.css
> +}
@realslimshanky fine. @CuriousLearner please review the PR with new changes.

2017-07-27 09:07 UTC, jasonbraganza commented
Can be closed now

2017-07-27 09:17 UTC, pradeepgangwar commented
@CuriousLearner Please see this. I think it can be merged now.

2017-08-01 06:54 UTC, sayanchowdhury approved these changes

2017-08-01 06:54 UTC, sayanchowdhury commented
LGTM :chocolate_bar:

2017-08-01 06:56 UTC, merged