[FIX #23] Added new twitter widget using twitter post fetcher
pythonindia/inpycon2017 pull request #66
Opened 2017-07-18 16:18 UTC by amitsin6h

Fixed the vacant space around twitter widget using https://github.com/jasonmayes/Twitter-Post-Fetcher.
Please review and let me know if some changes are required in css for designing the layout.

2017-07-22 05:37 UTC, CuriousLearner commented
Hey,

Thanks for your contributions.

This breaks on small screens. You need to handle for changes for all device less than `md` size.

Also, about the `reply`, `retweet`, `Favourite` shall be converted to buttons or something else. This doesn't look good in a link form.

2017-07-22 13:06 UTC, amitsin6h commented
@CuriousLearner ok thanks for your suggestion.

2017-07-23 12:42 UTC, amitsin6h commented
Old Preview of twitter latest post
![old-preview](https://user-images.githubusercontent.com/12906090/28499380-eb7c418c-6fa3-11e7-9019-468b8047f1c9.png)


New Preview of twitter latest post. Hope everyone like this also and also it's also responsive
![new-preview](https://user-images.githubusercontent.com/12906090/28499381-eb7ee446-6fa3-11e7-8de1-8dd006d42a39.png)

2017-07-23 22:08 UTC, realslimshanky approved these changes
LGTM.
Over to you @CuriousLearner

2017-08-02 05:12 UTC, CuriousLearner commented
@amitsin6h Thanks for your work. Can you please rebase your changes with the current HEAD at master?

You can do this while pulling from PyCon India repo like:

`git pull git@github.com:pythonindia/inpycon2017.git  master --rebase`

Then resolve conflicts if any, and regenerate the files again :) Let me know here if you need help.

2017-08-03 11:44 UTC, amitsin6h commented
@CuriousLearner I have made all the changes. Please review it

2017-08-03 12:52 UTC, sayanchowdhury requested changes

2017-08-03 12:52 UTC, sayanchowdhury commented on coc.html
> +    <script type="text/javascript" src="js/vendor/twitter-post-fetcher.js"></script>
Indentation.

2017-08-03 12:52 UTC, sayanchowdhury commented on coc.html
> +    <script type="text/javascript" src="js/vendor/twitter-post-fetcher-config.js"></script>
Indentation

2017-08-03 12:52 UTC, sayanchowdhury commented on index.html
> +						<!--************************************
There should be no blank spaces.

2017-08-03 12:52 UTC, sayanchowdhury commented on index.html
> +								<div id="pyconindiaTweets"></div>
Can we have a better id here, separated by hyphens `-`

2017-08-03 12:52 UTC, sayanchowdhury commented on js/vendor/twitter-post-fetcher-config.js
> +  "domId": 'pyconindiaTweets',
This would change accordingly.

2017-08-03 13:12 UTC, CuriousLearner commented on index.html
> +								<div id="pyconindiaTweets"></div>
Also, please keep them lower case separated by hyphens

2017-08-03 14:06 UTC, sayanchowdhury commented
You need to rebase the branch on top of `master` again

2017-08-03 19:50 UTC, amitsin6h reviewed
please review made the changes

2017-08-03 19:55 UTC, realslimshanky commented
There's a couple of UI bugs you need to fix on your code.
1) The twitter feed is breaking the page on mobile view due to text overflow.
* Exhibit A 
![Exhibit A](http://i.imgur.com/GgdLyJV.png)
* Exhibit B
![Exhibit B](http://i.imgur.com/6Tp5BSn.png)

Possible Fix -
* Wrap text inside 'tweet' div
* Make text overflow on the 'tweet' div inside 'timeline-content' div

2) 'Reply' button is little of towards right
* Exhibit A
![Exhibit A](http://i.imgur.com/1bsOBII.png)

Possible Fix -
* Try ul > li combination.

2017-08-04 07:47 UTC, amitsin6h reviewed
@realslimshanky please review it

2017-08-04 08:20 UTC, realslimshanky commented
Please check the buttons. The top one is still not aligned properly.

2017-08-04 09:22 UTC, amitsin6h reviewed
@realslimshanky fixed the top button. I tried to reduce the radius but still it didn't worked so I changed the view in the small screen. Let me know once you review it

2017-08-04 09:55 UTC, sayanchowdhury requested changes

2017-08-04 09:55 UTC, sayanchowdhury commented on templates/sections/_tweets.html
> +			*************************************-->
The indentation of the files are 2 spaces now.

2017-08-04 15:46 UTC, realslimshanky requested changes
Instead of a separate file for css you should add custom css inside main.css.
Your 'Twitter Post Fetcher' should go between 'Speakers Style' and 'Venue Style'.
Other than @sayanchowdhury 's review and this everything else LGTM.

2017-08-07 18:32 UTC, amitsin6h reviewed
@sayanchowdhury @realslimshanky Please review it.

2017-08-07 20:41 UTC, realslimshanky approved these changes
LGTM

2017-08-08 11:19 UTC, sayanchowdhury approved these changes

2017-08-08 12:55 UTC, CuriousLearner requested changes
Functionality wise, "LGTM" 

Please fix indentation in CSS and HTML file. Please use 2 spaces indentation to keep it consistent with the codebase. 

Once you're done, let me know and I'll merge it!

Thanks for your contribution!

2017-08-08 14:10 UTC, amitsin6h commented
but I did the same as the other html and css file was done. I mean the indentation

2017-08-08 16:44 UTC, amitsin6h reviewed
@CuriousLearner please review the indent

2017-08-08 16:45 UTC, amitsin6h commented
In my sublime text editor everything looks grate but I don't know why I get indentation problem.

2017-08-14 06:21 UTC, amitsin6h commented
@CuriousLearner

2017-08-16 05:06 UTC, CuriousLearner commented
@amitsin6h Apologies for getting to this late. 

Please use 2 spaces indentation (You're using tab for indentation. In sublime text editor select to spaces as indentation and keep tab size as 2).

And please do that only to files in templates folder and the css source files. Then you've to regenerate the html.

I hope that makes sense.

2017-08-17 04:46 UTC, amitsin6h reviewed
@CuriousLearner Please review it now. Used tab_size:2 in sublime. Hope this works

2017-08-17 05:05 UTC, CuriousLearner requested changes

2017-08-17 05:05 UTC, CuriousLearner commented on css/bootstrap.min.css
> - *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}body{margin:0}article,aside,details,
No need to touch default bootstrap file.

2017-08-17 05:05 UTC, CuriousLearner commented on templates/sections/_tweets.html
> +    		<div class="tg-sectionhead">
2 spaces indentation here as well (for the entire nested div)

2017-08-17 05:05 UTC, CuriousLearner commented on templates/index.html
> -
Indentation of this file is altered from default 2 space. Please fix.

2017-08-17 05:05 UTC, CuriousLearner commented on templates/sections/_tweets.html
> +*************************************-->
Leave a blank line at the end of the file.

2017-08-17 06:27 UTC, amitsin6h commented on css/bootstrap.min.css
> - *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}body{margin:0}article,aside,details,
the default bootstrap was creating problem in button so made some changes but the changes does not effect the website.

2017-08-17 06:28 UTC, CuriousLearner commented on css/bootstrap.min.css
> - *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}body{margin:0}article,aside,details,
If it is posing a problem, you're supposed to override style in your custom css file.

2017-08-17 07:29 UTC, amitsin6h reviewed
@CuriousLearner Please review it.

2017-08-17 08:36 UTC, CuriousLearner commented on templates/sections/_tweets.html
>      				<h2>Always Stay Updated</h2>
all the lines below.

Everything indented with 2 spaces.

2017-09-11 15:08 UTC, amitsin6h commented
#108 Please review it. Closing this PR

2017-09-11 15:08 UTC, closed without merging