FAQ updated with new ticket cancellation and transfer policies
pythonindia/inpycon2017 pull request #85
Opened 2017-07-30 18:02 UTC by realslimshanky

this fixes #84

2017-07-31 04:59 UTC, CuriousLearner commented
Looks good so far, please add about how the dev sprint entry works, on what ticket basis; etc.

2017-07-31 05:03 UTC, SaptakS commented on templates/faqs.html
> +														&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Early bird tickets cannot be canceled. They can only be transferred.<br>
Why use `&nbsp;` and not put the content inside a div and give the div margin/padding?

2017-07-31 05:37 UTC, sayanchowdhury commented on templates/faqs.html
> +														&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Early bird tickets cannot be canceled. They can only be transferred.<br>
:+1:

2017-07-31 09:37 UTC, realslimshanky commented on templates/faqs.html
> +														&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Early bird tickets cannot be canceled. They can only be transferred.<br>
I followed the format used on the page above. Let me try a better solution.

2017-07-31 09:51 UTC, CuriousLearner commented on templates/faqs.html
> +														&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Early bird tickets cannot be canceled. They can only be transferred.<br>
Can we please get this in by EOD today?

2017-07-31 10:08 UTC, realslimshanky commented on templates/faqs.html
> +														&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Early bird tickets cannot be canceled. They can only be transferred.<br>
I'm fixing it right now.

2017-07-31 10:28 UTC, realslimshanky commented
I'm done with the changes. Please review.

2017-08-01 06:47 UTC, CuriousLearner commented
@SaptakS @sayanchowdhury Please review this.

2017-08-01 06:50 UTC, CuriousLearner commented on faqs.html
> +													<p><span>A.</span>No, you don't have to buy a seperate ticket for Dev Sprint. But you'll need to have either a Conference Ticket or a Workshop Ticket to be able to enter Dev Sprint.</a><
Also, add here that due to space constraint, entry to Dev Sprints will be on first-come first-serve basis

2017-08-01 06:52 UTC, SaptakS commented
Looks good to me.

2017-08-01 06:52 UTC, sayanchowdhury requested changes

2017-08-01 06:52 UTC, sayanchowdhury commented on faqs.html
> +													<p class="tg-offset">- Breakfast, Lunch and Hi-Tea.<br>
High Tea

2017-08-01 06:52 UTC, sayanchowdhury commented on faqs.html
> +													<p><span>A.</span>No, you don't have to buy a seperate ticket for Dev Sprint. But you'll need to have either a Conference Ticket or a Workshop Ticket to be able to enter Dev Sprint.</a><
You should mention that there is limited space, so FCFS?

2017-08-01 06:53 UTC, sayanchowdhury commented
I have two suggestions other than that it looks good to merge. :cake:

2017-08-01 07:19 UTC, realslimshanky commented
@sayanchowdhury I've made changes according to your review.

2017-08-01 07:20 UTC, sayanchowdhury approved these changes

2017-08-01 07:21 UTC, sayanchowdhury commented
:taco:

2017-08-01 07:43 UTC, CuriousLearner approved these changes

2017-08-01 07:44 UTC, CuriousLearner requested changes

2017-08-01 07:44 UTC, CuriousLearner commented on faqs.html
> +													   - PyCon India T-shirt which will be distributed on Sep 25.</p>
This date should be changed to Nov 4 or removed entirely for now.

2017-08-01 08:41 UTC, realslimshanky commented on faqs.html
> +													   - PyCon India T-shirt which will be distributed on Sep 25.</p>
Sure. Changing to 4th.

2017-08-01 08:43 UTC, realslimshanky commented
@CuriousLearner date has been fixed.

2017-08-01 08:47 UTC, CuriousLearner approved these changes

2017-08-01 08:47 UTC, merged