#90 [UX/UI] Icon overlaps "Buy Tickets" button on mobile view
pythonindia/inpycon2017 pull request #91
Opened 2017-08-02 22:23 UTC by withshubh

updated media queries in the responsive.css file. No changes in the desktop version of the website only mobile version updated.

2017-08-03 06:49 UTC, sagarchoudhary96 commented
@withshubh Is this issue fixed or need to be looked?

2017-08-03 09:08 UTC, withshubh commented
FIxed

2017-08-03 14:11 UTC, sagarchoudhary96 commented
great :+1:

2017-08-03 20:09 UTC, realslimshanky requested changes
Please consider following changes.
* The changes you're making are on the responsive.css which is used by the entire website. You should always add or modify main.css since it contains page/element specific styles.
* You are targeting all the .tg-btn here to modify just one Ticket button. Instead of this use is or class specific to that particular button only.

2017-08-04 08:16 UTC, realslimshanky requested changes

2017-08-04 08:16 UTC, realslimshanky commented on index.html
> +									<a class="tg-btn tg-btnbookseat" style="color: #FFF;max-width: 80%" href="https://in.explara.com/e/pycon-india-2017" rel="noopener noreferrer">Buy Tickets</a>
Don't use inline style. Transfer these styles to main.css

2017-08-08 08:23 UTC, realslimshanky commented
@withshubh bro, 
* you have made change in the first commit and then revoked that change in the second.
* Then main some changes again in the third commit revoked that too in fourth.
* Made changes to index.html on fifth commit and revoked that change when I suggested you should transfer the style on stylesheet but you haven't added the styles yet. 
Feel free to ask for any assistance if you need.

2017-10-11 10:40 UTC, CuriousLearner commented
Is there any update on this @withshubh ? Will you able to do it?

2017-10-11 21:48 UTC, withshubh commented
@CuriousLearner "icon overlapping" bug from the website is already removed

2017-10-12 05:35 UTC, realslimshanky commented
Closing this PR since the same issue has already been fixed in #95

2017-10-12 05:35 UTC, closed without merging