[Fix #72] Hero screen size for all viewports
pythonindia/inpycon2017 pull request #92
Opened 2017-08-03 06:46 UTC by sagarchoudhary96

![screenshot from 2017-08-03 12-11-24](https://user-images.githubusercontent.com/16102594/28909214-1cef8798-7845-11e7-9289-20af3565f52b.png)

The hero screen was overflowing on mobile screens so i made it's height to 100vh so that it looks same on all devices. Below is the updated screenshot:

![screenshot from 2017-08-03 12-15-13](https://user-images.githubusercontent.com/16102594/28909290-7840e6be-7845-11e7-91e3-0ffd13f7fea5.png)

2017-08-03 19:45 UTC, pradeepgangwar commented
@sagarchoudhary96 resolve the conflicts. And after that give a **live link** of the changes made by you for reviewers to see the changes.

2017-08-03 19:53 UTC, sagarchoudhary96 commented
you can view the updated version [here.](https://sagarchoudhary96.github.io/inpycon2017/index.html)

2017-08-05 04:04 UTC, sagarchoudhary96 commented
@theskumar fixed the conflicts and provided live version link too

2017-08-08 01:33 UTC, sagarchoudhary96 commented
@theskumar please see to it

2017-08-08 08:09 UTC, realslimshanky commented
@sagarchoudhary96 problem with your fix is that it'll now work with the screen with small devices.
All the buttons get cramped into little space on the screen and it does not look good.
Exhibit A
![image](http://i.imgur.com/QAc4Kxs.png)

2017-08-09 18:28 UTC, sagarchoudhary96 commented
@realslimshanky but i think it looks better and the button were having that much magin before too i just made the  blue scren size too 100vh which didn't changed any no decreased the distances between buttons too

2017-08-10 13:19 UTC, realslimshanky commented
Sure. I'll leave this PR for others to review.

2017-08-12 16:37 UTC, sagarchoudhary96 commented
@realslimshanky is anybody looking to these PR's ?

2017-08-12 16:39 UTC, realslimshanky commented
@CuriousLearner @sayanchowdhury would you like to have a look into this?

2017-08-18 07:41 UTC, sagarchoudhary96 commented
@realslimshanky seems like no one looked at it. It would be great if you can see to it and let me know if required what changes to be made ?

2017-08-18 10:12 UTC, CuriousLearner requested changes
Left review inline.

Please ensure all the code you add is consistent with the code that is already there.

2017-08-18 10:12 UTC, CuriousLearner commented on css/main.css
> +	width:100%;
Please use 2 spaces indentation for the files.

2017-08-19 05:04 UTC, sagarchoudhary96 commented
@CuriousLearner I have made the required changes.

2017-08-23 20:27 UTC, sagarchoudhary96 commented
@realslimshanky @CuriousLearner would be great if you can look to it

2017-08-24 06:03 UTC, SaptakS requested changes

2017-08-24 06:03 UTC, SaptakS commented on css/main.css
> +.height-100vh {
What is the use of this class? Can you please explain? I don't see it being used anywhere. If not needed please remove.

2017-08-24 06:21 UTC, sagarchoudhary96 commented
@SaptakS removed it. I created it to use it in the index.html but later on i fixed it by making changes in css only. Just forgot to remove it. now it is removed.

2017-08-24 09:56 UTC, realslimshanky commented on css/responsive.css
> +@media (max-width:320px){}
What's the need of this media query?

2017-08-24 17:52 UTC, sagarchoudhary96 commented on css/responsive.css
> +@media (max-width:320px){}
this was no added by me it was already there in the code.

2017-08-24 19:02 UTC, realslimshanky commented on css/responsive.css
> +@media (max-width:320px){}
Please remove this line.

2017-08-25 07:37 UTC, sagarchoudhary96 commented on css/responsive.css
> +@media (max-width:320px){}
@realslimshanky removed it

2017-08-26 16:37 UTC, sagarchoudhary96 commented
@realslimshanky done👍

2017-10-04 12:55 UTC, sagarchoudhary96 commented
@CuriousLearner it has been too long please see to it

2023-07-25 23:36 UTC, closed without merging